//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoloniexAutoTrader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FPLU3UG2-0JESWKO0-BTO7M7VG-T5YY5RBA")]
        public string PublicKey {
            get {
                return ((string)(this["PublicKey"]));
            }
            set {
                this["PublicKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10b86d1251e795bdd5df6e18084f79a6d02423a68e2506fe7621be3f710c104802eefb0e2e591807e" +
            "a534daad5450ff12d1fe81bd50094177846a39e3f4a2153")]
        public string PrivateKey {
            get {
                return ((string)(this["PrivateKey"]));
            }
            set {
                this["PrivateKey"] = value;
            }
        }
    }
}
